# 公共配置文件
spring:
  application:
    name: loj-backend-gateway-service
  #nacos 配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: loj-user-service
#          uri: lb://loj-backend-user-service
#          predicates:
#            - Path=/api/user/**
#        - id: loj-question-service
#          uri: lb://loj-backend-question-service
#          predicates:
#            - Path=/api/question/**
#        - id: loj-judge-service
#          uri: lb://loj-backend-judge-service
#          predicates:
#            - Path=/api/judge/**
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    # host: localhost
    port: 6379
    timeout: 5000
server:
  address: 0.0.0.0
  port: 8100
  servlet:
    context-path: /api

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api/user/v3/api-docs?group=default
        service-name: loj-backend-user-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api/user
        order: 1
      - name: 题目服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api/question/v3/api-docs?group=default
        service-name: loj-backend-question-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api/question
        order: 2
      - name: 判题服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api/judge/v3/api-docs?group=default
        service-name: loj-backend-judge-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api/judge
        order: 3
